{% set version = "2.4.1" %}
{% set sha256 = "4591c360c5b1f090fee18a03da501790341f873dcdc41b10036594edb52bba54" %}

package:
  name: get_fasta_info
  version: '{{ version }}'

source:
  url: https://github.com/nylander/get_fasta_info/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - autoconf
    - automake
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - get_fasta_info -h 2>/dev/null
    - get_fastq_info -h 2>/dev/null

about:
  home: https://github.com/nylander/get_fasta_info
  license: MIT
  license_file: LICENSE
  summary: "get_FAST{A,Q}_info - Get fast info on fasta and fastq files"
